---
# Stop and disable os-collect-config
#
# Run from the tripleo-ansible directory:
#
- name: "Disable os-collect-config service"
  sudo: yes
  service: name=os-collect-config enabled=no state=stopped
- name: "Reconfigure os-collect-config for local collector"
  sudo: yes
  copy:
    src: files/os-collect-config.conf
    dest: /etc/os-collect-config.conf
