- name: examine heat facts
  hosts: localhost
  tasks:
  - name: display facts from heat
    local_action:
        module: heat_facts
        region_name: regionOne
        login_username: '{{ lookup("env", "OS_USERNAME") }}'
        login_password: '{{ lookup("env", "OS_PASSWORD") }}'
        login_tenant_name: '{{ lookup("env", "OS_TENANT_NAME") }}'
        auth_url: '{{ lookup("env", "OS_AUTH_URL") }}'
        stacks: all

  - name: Stacks debug info
    debug: msg="Stack Name {{ item.key }}, stack status {{ item.value.heat_stack_status }}"
    with_dict: heat_stacks
  - name: Instances debug info
    debug: msg="Instance Name {{ item.key }}, instance resource type {{ item.value.heat_resource_type }}"
    with_dict: heat_instances
