# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: examine heat facts
  hosts: localhost
  tasks:
  - name: display facts from heat
    local_action:
        module: heat_facts
        region_name: regionOne
        login_username: '{{ lookup("env", "OS_USERNAME") }}'
        login_password: '{{ lookup("env", "OS_PASSWORD") }}'
        login_tenant_name: '{{ lookup("env", "OS_TENANT_NAME") }}'
        auth_url: '{{ lookup("env", "OS_AUTH_URL") }}'
        stacks: all

  - name: Stacks debug info
    debug: msg="Stack Name {{ item.key }}, stack status {{ item.value.heat_stack_status }}"
    with_dict: heat_stacks
  - name: Instances debug info
    debug: msg="Instance Name {{ item.key }}, instance resource type {{ item.value.heat_resource_type }}"
    with_dict: heat_instances
