---
- hosts: nova-compute
  name: "Enable OpenStack Compute"
  tasks:
    - service: name={{ item }} enabled=yes state=started
      with_items: compute-services | reverse
- hosts: controller
  name: "Enable OpenStack Controller Services"
  tasks:
    - service: name={{ item }} enabled=yes state=started
      with_items: control-services | reverse
- hosts: undercloud
  name: "Enable OpenStack Undercloud Services"
  tasks:
    - service: name={{ item }} enabled=yes state=started
      with_items: undercloud-services | reverse
