---
- hosts: controller
  name: Enable Overcloud Controller
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=yes state=started
      with_items: overcloud_controller_services
- hosts: nova-compute
  name: Enable Overcloud Compute
  sudo: yes
  tasks:
    - name: "Run os-collect-config"
      sudo: yes
      command: os-collect-config --force --one
    - service: name={{ item }} enabled=yes state=started
      with_items: overcloud_compute_services
- hosts: undercloud
  name: Enable Undercloud
  sudo: yes
  tasks:
    - service: name={{ item }} enabled=yes state=started
      with_items: undercloud_services
