- name: rebuild an instance
  nova_rebuild:
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    login_tenant_name: "{{ os_tenant_name }}"
    auth_url: "{{ os_auth_url }}"
    region_name: "{{ os_region_name }}"
    name: "{{ name }}"
    image_id: "{{ image_id }}"
    wait_for: "{{ wait_for }}"
